# Generated by Django 3.0.5 on 2020-04-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_coco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoCo',
            new_name='CoCo2',
        ),
    ]
