# Generated by Django 3.0.5 on 2020-04-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200419_1552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoCo2',
            new_name='CoCo',
        ),
    ]
