# Generated by Django 3.0.5 on 2020-05-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200512_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerchild',
            name='ID_C',
            field=models.CharField(max_length=9),
        ),
    ]
