# Generated by Django 3.0.5 on 2020-06-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userprofile_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoursReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=9)),
                ('start_hour', models.TimeField()),
                ('finish_hour', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
