# Generated by Django 3.0.5 on 2020-06-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_hoursreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoursreport',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hoursreport',
            name='finish_hour',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hoursreport',
            name='start_hour',
            field=models.CharField(max_length=20),
        ),
    ]
