# Generated by Django 3.0.5 on 2020-04-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='t_id',
            field=models.PositiveIntegerField(default=99, unique=True),
            preserve_default=False,
        ),
    ]
