# Generated by Django 3.0.5 on 2020-04-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='slug',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='t_id',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
