# Generated by Django 3.0.5 on 2020-04-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200418_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoCo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yellow', models.CharField(max_length=10)),
            ],
        ),
    ]
