# Generated by Django 3.0.5 on 2020-04-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200419_1556'),
        ('users', '0003_auto_20200419_1422'),
    ]

    operations = [
    ]
