# Generated by Django 3.0.5 on 2020-05-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20200421_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_P', models.CharField(max_length=200)),
                ('ID_C', models.CharField(max_length=9, unique=True)),
                ('FName_C', models.CharField(max_length=20)),
                ('LName_C', models.CharField(max_length=20)),
                ('Age_C', models.CharField(max_length=10)),
                ('Phone_P', models.CharField(max_length=10)),
                ('idClass', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='CoCo',
        ),
    ]
